name: Unit Tests

on:
    workflow_run:
        workflows: [ "CI-CD" ]
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Install dependencies
                run: npx yarn
            -   uses: actions/download-artifact@v3
                with:
                    path: dist
            -   name: Run tests
                run: npx yarn test